name: Building New Kernel

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v2
    - name: Compile Kernel
      env:
        GIT_SECRET: ${{ secrets.GIT_SECRET }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      run: |
        chmod +x dtc10.sh
        bash dtc10.sh 
